apiVersion: v2
# upstream version
appVersion: APP_VERSION_PLACEHOLDER
name: kube-vip
# giantswarm chart version
version: CHART_VERSION_PLACEHOLDER
description: A Helm chart for kube-vip
home: https://github.com/giantswarm/kube-vip-app
icon: https://s.giantswarm.io/app-icons/kube-vip/1/light.png
annotations:
  io.giantswarm.application.audience: "all"
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "rocket"
  io.giantswarm.application.upstream-chart-url: "https://github.com/kube-vip/helm-charts/tree/main/charts/kube-vip"
  io.giantswarm.application.upstream-chart-version: "APP_VERSION_PLACEHOLDER"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
sources:
  - https://github.com/kube-vip/helm-charts
